name: Build, test and push

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - apache
          - apache-gssapi
          - apache-fpm-gssapi
          - client
          - dc

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/Dockerfile
          tags: icewind1991/samba-krb-test-${{ matrix.image }}:latest
          outputs: type=docker,dest=/tmp/${{ matrix.image }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar

  test:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        variant:
          - ""
          - "-gssapi"
          - "-fpm-gssapi"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout smb
        uses: actions/checkout@v3
        with:
          repository: icewind1991/smb
          path: smb
      - name: Setup smb
        run: |
          cd smb
          composer i
          cd ..
      - name: Download dc image
        uses: actions/download-artifact@v3
        with:
          path: /tmp
          name: dc
      - name: Download apache image
        uses: actions/download-artifact@v3
        with:
          path: /tmp
          name: apache${{ matrix.variant }}
      - name: Download client image
        uses: actions/download-artifact@v3
        with:
          path: /tmp
          name: client
      - name: Load Docker images
        run: |
          docker load --input /tmp/apache${{ matrix.variant }}.tar
          docker load --input /tmp/client.tar
          docker load --input /tmp/dc.tar
          docker image ls -a
      - name: Run smb kerberos SSO
        run: |
          DC_IP=$(./start-dc.sh)

          echo "DC: $DC_IP"

          # start apache
          APACHE_IP=$(./start-apache.sh $DC_IP $PWD/smb ${{ matrix.variant }})
          echo "APACHE: $APACHE_IP"
          
          docker ps -a

          LIST=$(./client-cmd.sh $DC_IP curl --negotiate -u testuser@DOMAIN.TEST: --delegation always http://httpd.domain.test/example-apache-kerberos.php)

          echo $LIST

          LIST=$(echo $LIST | tr -d '[:space:]')

          [[ $LIST == "test.txt" ]]

  push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - apache
          - apache-gssapi
          - apache-fpm-gssapi
          - client
          - dc
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: icewind1991
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download ${{ matrix.image }} image
        uses: actions/download-artifact@v3
        with:
          path: /tmp
          name: ${{ matrix.image }}
      - name: Load ${{ matrix.image }} image
        run: |
          docker load --input /tmp/${{ matrix.image }}.tar
      - name: Push ${{ matrix.image }} image
        run: |
          docker push icewind1991/samba-krb-test-${{ matrix.image }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push ${{ matrix.image }} image to ghcr.io
        run: |
          docker tag icewind1991/samba-krb-test-${{ matrix.image }} ghcr.io/icewind1991/samba-krb-test-${{ matrix.image }}
          docker push ghcr.io/icewind1991/samba-krb-test-${{ matrix.image }}
